HISTORICAL_LIBRARY = [
    # ------------------------------------------------------------------
    # GAMES
    # ------------------------------------------------------------------
    {
        "media_type": "game",
        "title": "Mario Kart DS",
        "genre": "Racing",
        "date_consumed": "2025-01-01",
        "method": "3 stars all cups",
        "hardware": "nds",
        "scores": {
            "story": 1,
            "gameplay": 5,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 1,
            "replay": 5,
        },
        "historical_score": 74.29,
    },
    {
        "media_type": "game",
        "title": "Super Mario Land",
        "genre": "Platformer",
        "date_consumed": "2025-01-21",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 1,
            "gameplay": 4,
            "art": 4,
            "audio": 4,
            "creativity": 1,
            "emotion": 1,
            "replay": 1,
        },
        "historical_score": 45.71,
    },
    {
        "media_type": "game",
        "title": "Kirby's Block Ball",
        "genre": "Block breaker / Pinball",
        "date_consumed": "2025-01-22",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 4,
            "audio": 4,
            "creativity": 5,
            "emotion": 1,
            "replay": 4,
        },
        "historical_score": 77.14,
    },
    {
        "media_type": "game",
        "title": "Super Mario Land 2: 6 Golden Coins",
        "genre": "Platformer",
        "date_consumed": "2025-01-23",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 1,
            "gameplay": 4,
            "art": 4,
            "audio": 4,
            "creativity": 1,
            "emotion": 1,
            "replay": 1,
        },
        "historical_score": 45.71,
    },
    {
        "media_type": "game",
        "title": "Wario Land: Super Mario Land 3",
        "genre": "Platformer",
        "date_consumed": "2025-01-27",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 4,
            "audio": 4,
            "creativity": 4,
            "emotion": 1,
            "replay": 4,
        },
        "historical_score": 74.29,
    },
    {
        "media_type": "game",
        "title": "Mega Man 2",
        "genre": "Platformer",
        "date_consumed": "2025-01-29",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 4,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 1,
            "replay": 4,
        },
        "historical_score": 77.14,
    },
    {
        "media_type": "game",
        "title": "Ducktales",
        "genre": "Platformer",
        "date_consumed": "2025-01-30",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 1,
            "replay": 4,
        },
        "historical_score": 80.00,
    },
    {
        "media_type": "game",
        "title": "Kirby's Adventure",
        "genre": "Platformer",
        "date_consumed": "2025-02-04",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 5,
            "audio": 4,
            "creativity": 4,
            "emotion": 1,
            "replay": 1,
        },
        "historical_score": 68.57,
    },
    {
        "media_type": "game",
        "title": "Kirby's Dream Land",
        "genre": "Platformer",
        "date_consumed": "2025-02-05",
        "method": "Credits",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 5,
            "audio": 4,
            "creativity": 4,
            "emotion": 1,
            "replay": 1,
        },
        "historical_score": 68.57,
    },
    {
        "media_type": "game",
        "title": "SMT: Strange Journey Redux",
        "genre": "Rpg",
        "date_consumed": "2025-05-14",
        "method": "Credits - 90 hours",
        "hardware": "3ds",
        "scores": {
            "story": 5,
            "gameplay": 5,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 5,
            "replay": 4,
        },
        "historical_score": 94.29,
    },
    {
        "media_type": "game",
        "title": "Wario Land II",
        "genre": "Platformer",
        "date_consumed": "2025-08-11",
        "method": "Credits ~50% completed",
        "hardware": "r36s",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 4,
            "audio": 4,
            "creativity": 4,
            "emotion": 1,
            "replay": 5,
        },
        "historical_score": 77.14,
    },
    {
        "media_type": "game",
        "title": "Trace Memory",
        "genre": "Visual Novel",
        "date_consumed": "2025-09-05",
        "method": "Credits",
        "hardware": "nds",
        "scores": {
            "story": 5,
            "gameplay": 4,
            "art": 5,
            "audio": 4,
            "creativity": 4,
            "emotion": 5,
            "replay": 0,
        },
        "historical_score": 77.14,
    },
    {
        "media_type": "game",
        "title": "Mario and Luigi Superstar Saga",
        "genre": "Rpg",
        "date_consumed": "2025-09-09",
        "method": "Credits - 25 hours",
        "hardware": "3ds",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 5,
            "audio": 4,
            "creativity": 4,
            "emotion": 1,
            "replay": 4,
        },
        "historical_score": 77.14,
    },
    {
        "media_type": "game",
        "title": "Chase: Cold Case investigations - Distant Memories",
        "genre": "Visual Novel",
        "date_consumed": "2025-09-16",
        "method": "Credits",
        "hardware": "3ds",
        "scores": {
            "story": 3,
            "gameplay": 2,
            "art": 4,
            "audio": 5,
            "creativity": 0,
            "emotion": 4,
            "replay": 0,
        },
        "historical_score": 51.43,
    },
    {
        "media_type": "game",
        "title": "Nine Hours Nine Persons Nine Doors",
        "genre": "Visual Novel",
        "date_consumed": "2025-10-07",
        "method": "5 / 6 endings: submarine, knife, safe, June, coffin",
        "hardware": "3ds",
        "scores": {
            "story": 5,
            "gameplay": 3,
            "art": 5,
            "audio": 4,
            "creativity": 3,
            "emotion": 5,
            "replay": 5,
        },
        "historical_score": 85.71,
    },
    {
        "media_type": "game",
        "title": "Doki Doki Literature Club",
        "genre": "Visual Novel",
        "date_consumed": "2025-10-20",
        "method": "Credits, True Ending, Monika Deletes the Game",
        "hardware": "pc",
        "scores": {
            "story": 5,
            "gameplay": 4,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 4,
            "replay": 4,
        },
        "historical_score": 88.57,
    },
    {
        "media_type": "game",
        "title": "Hotel Dusk: Room 215",
        "genre": "Visual Novel",
        "date_consumed": "2025-10-31",
        "method": "Credits",
        "hardware": "3ds",
        "scores": {
            "story": 5,
            "gameplay": 3,
            "art": 5,
            "audio": 3,
            "creativity": 3,
            "emotion": 5,
            "replay": 1,
        },
        "historical_score": 71.43,
    },
    {
        "media_type": "game",
        "title": "Last Window: The Secret of Cape West",
        "genre": "Visual Novel",
        "date_consumed": "2025-11-10",
        "method": "Credits",
        "hardware": "3ds",
        "scores": {
            "story": 4,
            "gameplay": 3,
            "art": 5,
            "audio": 4,
            "creativity": 3,
            "emotion": 5,
            "replay": 1,
        },
        "historical_score": 71.43,
    },
    {
        "media_type": "game",
        "title": "Eco Fighters",
        "genre": "Shoot em up",
        "date_consumed": "2025-11-20",
        "method": "Credits, unlimited quarters",
        "hardware": "r36s",
        "scores": {
            "story": 3,
            "gameplay": 4,
            "art": 5,
            "audio": 3,
            "creativity": 2,
            "emotion": 0,
            "replay": 4,
        },
        "historical_score": 60.00,
    },
    {
        "media_type": "game",
        "title": "Zero Escape: Virtue's Last Reward",
        "genre": "Visual Novel",
        "date_consumed": "2025-12-08",
        "method": "All endings + true ending - 49 hours",
        "hardware": "3ds",
        "scores": {
            "story": 5,
            "gameplay": 4,
            "art": 5,
            "audio": 5,
            "creativity": 4,
            "emotion": 5,
            "replay": 5,
        },
        "historical_score": 94.29,
    },
    {
        "media_type": "game",
        "title": "Luigi's Mansion: Dark Moon",
        "genre": "Action Adventure",
        "date_consumed": "2025-12-21",
        "method": "Credits",
        "hardware": "3ds",
        "scores": {
            "story": 4,
            "gameplay": 5,
            "art": 4,
            "audio": 5,
            "creativity": 5,
            "emotion": 4,
            "replay": 5,
        },
        "historical_score": 91.43,
    },
    {
        "media_type": "game",
        "title": "Zero Time Dilemma",
        "genre": "Visual Novel",
        "date_consumed": "2026-01-05",
        "method": "All endings, all fragments, ~37 hours",
        "hardware": "3ds",
        "scores": {
            "story": 4,
            "gameplay": 4,
            "art": 4,
            "audio": 3,
            "creativity": 4,
            "emotion": 5,
            "replay": 5,
        },
        "historical_score": 82.86,
    },
    {
        "media_type": "game",
        "title": "Time Hollow",
        "genre": "Visual Novel",
        "date_consumed": "2026-01-17",
        "method": "Post credits scene",
        "hardware": "nds",
        "scores": {
            "story": 4.8,
            "gameplay": 4,
            "art": 5,
            "audio": 4.8,
            "creativity": 3.9,
            "emotion": 5,
            "replay": 4,
        },
        "historical_score": 90.00,
    },
    {
        "media_type": "game",
        "title": "Phoenix Wright: Ace Attorney",
        "genre": "Visual Novel",
        "date_consumed": "2026-01-28",
        "method": "Finished chapter 4 - credits",
        "hardware": "nds",
        "scores": {
            "story": 4.5,
            "gameplay": 4,
            "art": 4.8,
            "audio": 4.5,
            "creativity": 3.5,
            "emotion": 4.8,
            "replay": 3,
        },
        "historical_score": 83.14,
    },
    {
        "media_type": "game",
        "title": "Phoenix Wright: Ace Attorney Chapter 5",
        "genre": "Visual Novel",
        "date_consumed": "2026-02-03",
        "method": "Credits",
        "hardware": "nds",
        "scores": {
            "story": 4.6,
            "gameplay": 4,
            "art": 4.8,
            "audio": 4.5,
            "creativity": 3.6,
            "emotion": 4.8,
            "replay": 3,
        },
        "historical_score": 83.71,
    },
    {
        "media_type": "game",
        "title": "Mario Kart 64",
        "genre": "Racing",
        "date_consumed": "2026-02-14",
        "method": "All gold cups",
        "hardware": "r36s",
        "scores": {
            "story": 2,
            "gameplay": 4.5,
            "art": 4,
            "audio": 4.8,
            "creativity": 4.25,
            "emotion": 1,
            "replay": 5,
        },
        "historical_score": 73.00,
    },
    {
        "media_type": "game",
        "title": "The World Ends with You",
        "genre": "Rpg",
        "date_consumed": "2026-03-15",
        "method": "Stuck on final boss",
        "hardware": "3ds",
        "scores": {
            "story": 4.5,
            "gameplay": 4.5,
            "art": 4.8,
            "audio": 4.9,
            "creativity": 4.75,
            "emotion": 4.25,
            "replay": 2,
        },
        "historical_score": 84.86,
    },
    {
        "media_type": "game",
        "title": "Ghost Trick",
        "genre": "Puzzle",
        "date_consumed": "2026-04-25",
        "method": "Credits",
        "hardware": "3ds",
        "scores": {
            "story": 4.75,
            "gameplay": 4.75,
            "art": 5,
            "audio": 5,
            "creativity": 4.9,
            "emotion": 4.75,
            "replay": 1,
        },
        "historical_score": 86.14,
    },

    # ------------------------------------------------------------------
    # VIDEOS
    # ------------------------------------------------------------------
    {
        "media_type": "video",
        "title": "Coherence",
        "genre": "Mind-Bending Sci-Fi / Psychological Thriller",
        "date_consumed": "2025-11-17",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "Beyond the Infinite Two Minutes",
        "genre": "Whimsical / Light Sci-Fi",
        "date_consumed": "2025-11-17",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "Lake Mungo",
        "genre": "Psychological Horror / Grief Horror",
        "date_consumed": "2025-11-18",
        "scores": {
            "entertaining": 3,
            "engaging": 4,
            "thought_provoking": 3,
            "pacing": 3,
            "writing": 4,
            "music_sound": 4,
        },
        "historical_score": 70.00,
    },
    {
        "media_type": "video",
        "title": "Enemy",
        "genre": "Surreal Psychological Thriller",
        "date_consumed": "2025-11-18",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 3,
            "writing": 3,
            "music_sound": 3,
        },
        "historical_score": 70.00,
    },
    {
        "media_type": "video",
        "title": "The Invitation (2015)",
        "genre": "Psychological Thriller / Slow-Burn Horror",
        "date_consumed": "2025-11-19",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 5,
            "pacing": 4,
            "writing": 5,
            "music_sound": 4,
        },
        "historical_score": 86.67,
    },
    {
        "media_type": "video",
        "title": "Resolution",
        "genre": "Psychological Horror / Cosmic Mystery",
        "date_consumed": "2025-11-19",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 4,
            "writing": 5,
            "music_sound": 4,
        },
        "historical_score": 83.33,
    },
    {
        "media_type": "video",
        "title": "The Endless",
        "genre": "Cosmic Horror / Sci-Fi Mystery",
        "date_consumed": "2025-11-20",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "Portal: No Escape",
        "genre": "Mind-Bending Sci-Fi / Identity & Time",
        "date_consumed": "2025-11-24",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 3,
            "pacing": 5,
            "writing": 4,
            "music_sound": 3,
        },
        "historical_score": 83.33,
    },
    {
        "media_type": "video",
        "title": "Curve (Short - 2015)",
        "genre": "Minimalist / Single-Location Horror",
        "date_consumed": "2025-11-24",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 3,
            "pacing": 4,
            "writing": 3,
            "music_sound": 4,
        },
        "historical_score": 80.00,
    },
    {
        "media_type": "video",
        "title": "The Lighthouse",
        "genre": "Psychological Horror",
        "date_consumed": "2025-11-24",
        "scores": {
            "entertaining": 4,
            "engaging": 4.5,
            "thought_provoking": 4,
            "pacing": 4,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 88.33,
    },
    {
        "media_type": "video",
        "title": "Mira (2023 short)",
        "genre": "Psychological / Surreal Horror (Animated)",
        "date_consumed": "2025-11-24",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 4,
            "writing": 3,
            "music_sound": 5,
        },
        "historical_score": 80.00,
    },
    {
        "media_type": "video",
        "title": "The One I Love",
        "genre": "Surreal Romantic Thriller / Sci-Fi Dramedy",
        "date_consumed": "2025-12-01",
        "scores": {
            "entertaining": 3,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 4,
            "writing": 3,
            "music_sound": 3,
        },
        "historical_score": 70.00,
    },
    {
        "media_type": "video",
        "title": "Synchronic",
        "genre": "Emotional Drama / Trippy Sci-Fi",
        "date_consumed": "2025-12-05",
        "scores": {
            "entertaining": 3,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 2,
            "writing": 3,
            "music_sound": 3,
        },
        "historical_score": 63.33,
    },
    {
        "media_type": "video",
        "title": "Exam",
        "genre": "Psychological Thriller / Single-Location Drama",
        "date_consumed": "2025-12-11",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 4,
            "writing": 4,
            "music_sound": 3,
        },
        "historical_score": 86.67,
    },
    {
        "media_type": "video",
        "title": "Wake Up Dead Man: A Knives Out Mystery",
        "genre": "Mystery / Whodunit",
        "date_consumed": "2025-12-14",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "The Elephant",
        "genre": "Surreal Absurdist Horror",
        "date_consumed": "2025-12-27",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 5,
            "pacing": 4,
            "writing": 4,
            "music_sound": 5,
        },
        "historical_score": 86.67,
    },
    {
        "media_type": "video",
        "title": "One Battle After Another",
        "genre": "Crime Thriller",
        "date_consumed": "2025-12-28",
        "scores": {
            "entertaining": 4,
            "engaging": 5,
            "thought_provoking": 4,
            "pacing": 3,
            "writing": 5,
            "music_sound": 4,
        },
        "historical_score": 83.33,
    },
    {
        "media_type": "video",
        "title": "Five Nights at Freddy's 2",
        "genre": "Supernatural Horror",
        "date_consumed": "2025-12-28",
        "scores": {
            "entertaining": 3,
            "engaging": 3,
            "thought_provoking": 2,
            "pacing": 4,
            "writing": 3,
            "music_sound": 4,
        },
        "historical_score": 63.33,
    },
    {
        "media_type": "video",
        "title": "Avatar",
        "genre": "Epic Sci-Fi / Adventure",
        "date_consumed": "2025-12-31",
        "scores": {
            "entertaining": 3,
            "engaging": 2,
            "thought_provoking": 1,
            "pacing": 3,
            "writing": 3,
            "music_sound": 3,
        },
        "historical_score": 50.00,
    },
    {
        "media_type": "video",
        "title": "Avatar: Fire and Ash",
        "genre": "Epic Sci-Fi / Adventure",
        "date_consumed": "2026-01-01",
        "scores": {
            "entertaining": 3,
            "engaging": 2,
            "thought_provoking": 1,
            "pacing": 2,
            "writing": 2,
            "music_sound": 3,
        },
        "historical_score": 43.33,
    },
    {
        "media_type": "video",
        "title": "Bugonia",
        "genre": "Absurdist Paranoia / Sci-Fi Satire",
        "date_consumed": "2026-01-04",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 4.5,
            "writing": 5,
            "music_sound": 5.5,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "The Rug by Mythic Productions",
        "genre": "Horror-Comedy Short",
        "date_consumed": "2026-01-05",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 4.5,
            "pacing": 5,
            "writing": 4.5,
            "music_sound": 4.25,
        },
        "historical_score": 94.17,
    },
    {
        "media_type": "video",
        "title": "Weapons",
        "genre": "Psychological Horror / Mystery Thriller",
        "date_consumed": "2026-01-18",
        "scores": {
            "entertaining": 4.8,
            "engaging": 5,
            "thought_provoking": 4.8,
            "pacing": 4.5,
            "writing": 4.8,
            "music_sound": 4.25,
        },
        "historical_score": 93.83,
    },
    {
        "media_type": "video",
        "title": "One Hour Photo",
        "genre": "Psychological Thriller",
        "date_consumed": "2026-01-24",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.5,
            "thought_provoking": 4,
            "pacing": 4,
            "writing": 4.5,
            "music_sound": 4.8,
        },
        "historical_score": 87.67,
    },
    {
        "media_type": "video",
        "title": "The Platform",
        "genre": "Dystopian Horror",
        "date_consumed": "2026-02-16",
        "scores": {
            "entertaining": 4.25,
            "engaging": 4.25,
            "thought_provoking": 4,
            "pacing": 4.25,
            "writing": 4.25,
            "music_sound": 4,
        },
        "historical_score": 83.33,
    },
    {
        "media_type": "video",
        "title": "Triangle",
        "genre": "Psychological Thriller / Time-Loop Horror / Single-Location",
        "date_consumed": "2026-02-20",
        "scores": {
            "entertaining": 4.9,
            "engaging": 4.9,
            "thought_provoking": 5,
            "pacing": 4.9,
            "writing": 5,
            "music_sound": 5.1,
        },
        "historical_score": 99.33,
    },
    {
        "media_type": "video",
        "title": "Infinity Chamber",
        "genre": "Mind-Bending Sci-Fi / Psychological Thriller / Minimalist",
        "date_consumed": "2026-02-24",
        "scores": {
            "entertaining": 4.8,
            "engaging": 4.8,
            "thought_provoking": 5,
            "pacing": 4.8,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 98.00,
    },
    {
        "media_type": "video",
        "title": "Ready Or Not",
        "genre": "Horror-Comedy / Survival Thriller / Satirical Social Horror",
        "date_consumed": "2026-03-14",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 4.9,
            "pacing": 5,
            "writing": 4.9,
            "music_sound": 5,
        },
        "historical_score": 99.33,
    },
    {
        "media_type": "video",
        "title": "mother!",
        "genre": "Psychological Horror / Surreal Allegory",
        "date_consumed": "2026-03-16",
        "scores": {
            "entertaining": 4.5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 4.5,
            "writing": 4.5,
            "music_sound": 4.9,
        },
        "historical_score": 94.67,
    },
    {
        "media_type": "video",
        "title": "Bad Times at the El Royale",
        "genre": "Neo-Noir Crime Thriller",
        "date_consumed": "2026-03-28",
        "scores": {
            "entertaining": 4.25,
            "engaging": 4,
            "thought_provoking": 3.5,
            "pacing": 4.25,
            "writing": 4.8,
            "music_sound": 5,
        },
        "historical_score": 86.00,
    },
    {
        "media_type": "video",
        "title": "The Vast of Night",
        "genre": "Sci-fi Mystery",
        "date_consumed": "2026-04-21",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.67,
            "thought_provoking": 4.8,
            "pacing": 4.67,
            "writing": 4.99,
            "music_sound": 4.75,
        },
        "historical_score": 94.60,
    },
    {
        "media_type": "video",
        "title": "Project Hail Mary",
        "genre": "Sci-Fi",
        "date_consumed": "2026-04-26",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 4.99,
            "pacing": 5,
            "writing": 5,
            "music_sound": 4.75,
        },
        "historical_score": 99.13,
    },
    {
        "media_type": "video",
        "title": "Sorry to Bother You",
        "genre": "Absurdist Satire / Surreal Reality-Break",
        "date_consumed": "2026-04-29",
        "scores": {
            "entertaining": 4.8,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5.1,
            "writing": 5.2,
            "music_sound": 4.8,
        },
        "historical_score": 99.67,
    },
    {
        "media_type": "video",
        "title": "They Cloned Tyrone",
        "genre": "Surreal Sci-Fi Noir Satire",
        "date_consumed": "2026-05-05",
        "scores": {
            "entertaining": 5,
            "engaging": 5,
            "thought_provoking": 4.9,
            "pacing": 4.8,
            "writing": 5.1,
            "music_sound": 5.2,
        },
        "historical_score": 100.00,
    },
    {
        "media_type": "video",
        "title": "Ready Or Not, Here I Come",
        "genre": "Horror-Comedy / Survival Thriller / Satirical Social Horror",
        "date_consumed": "2026-05-09",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4,
            "thought_provoking": 4,
            "pacing": 5,
            "writing": 4,
            "music_sound": 4.5,
        },
        "historical_score": 86.67,
    },
    {
        "media_type": "video",
        "title": "Final Destination Bloodlines",
        "genre": "Supernatural Horror",
        "date_consumed": "2026-05-16",
        "scores": {
            "entertaining": 4,
            "engaging": 4,
            "thought_provoking": 3,
            "pacing": 4.5,
            "writing": 4.5,
            "music_sound": 5,
        },
        "historical_score": 83.33,
    },
    {
        "media_type": "video",
        "title": "The Man From Earth",
        "genre": "Minimalist Philosophical Sci-Fi",
        "date_consumed": "2026-05-19",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.5,
            "thought_provoking": 4.9,
            "pacing": 4.5,
            "writing": 4.75,
            "music_sound": 4.75,
        },
        "historical_score": 93.00,
    },
    {
        "media_type": "video",
        "title": "Mike & Nick & Nick & Alice",
        "genre": "Sci-Fi Action Comedy",
        "date_consumed": "2026-05-24",
        "scores": {
            "entertaining": 4,
            "engaging": 3.5,
            "thought_provoking": 3,
            "pacing": 4,
            "writing": 3.75,
            "music_sound": 5,
        },
        "historical_score": 77.50,
    },
    {
        "media_type": "video",
        "title": "The Backrooms",
        "genre": "Horror",
        "date_consumed": "2026-06-01",
        "scores": {
            "entertaining": 5,
            "engaging": 5.1,
            "thought_provoking": 5.1,
            "pacing": 5,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 100.33,
    },
    {
        "media_type": "video",
        "title": "Caught Stealing",
        "genre": "Action",
        "date_consumed": "2026-06-06",
        "scores": {
            "entertaining": 3,
            "engaging": 3.2,
            "thought_provoking": 2,
            "pacing": 4,
            "writing": 3.5,
            "music_sound": 3.5,
        },
        "historical_score": 64.00,
    },
    {
        "media_type": "video",
        "title": "Angel's Egg",
        "genre": "Anime Sci-Fi",
        "date_consumed": "2026-06-12",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4,
            "thought_provoking": 5,
            "pacing": 3.5,
            "writing": 4.25,
            "music_sound": 5.1,
        },
        "historical_score": 87.83,
    },
    {
        "media_type": "video",
        "title": "Companion",
        "genre": "Sci-Fi Thriller",
        "date_consumed": "2026-06-14",
        "scores": {
            "entertaining": 4.75,
            "engaging": 5,
            "thought_provoking": 4.75,
            "pacing": 5,
            "writing": 5,
            "music_sound": 4.8,
        },
        "historical_score": 97.67,
    },
    {
        "media_type": "video",
        "title": "Undertone",
        "genre": "Horror Thriller",
        "date_consumed": "2026-06-21",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4,
            "thought_provoking": 4.75,
            "pacing": 4,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 90.83,
    },
    {
        "media_type": "video",
        "title": "Umma",
        "genre": "Ghost / Horror",
        "date_consumed": "2026-06-30",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.8,
            "thought_provoking": 4,
            "pacing": 4.5,
            "writing": 4,
            "music_sound": 4.25,
        },
        "historical_score": 86.83,
    },
    {
        "media_type": "video",
        "title": "The Backrooms: Everything Must Go Edition",
        "genre": "Horror",
        "date_consumed": "2026-07-08",
        "scores": {
            "entertaining": 5,
            "engaging": 5.1,
            "thought_provoking": 5.1,
            "pacing": 5,
            "writing": 5.1,
            "music_sound": 5,
        },
        "historical_score": 101.00,
    },
    {
        "media_type": "video",
        "title": "Skinamarink",
        "genre": "Horror",
        "date_consumed": "2026-07-09",
        "scores": {
            "entertaining": 4,
            "engaging": 5.1,
            "thought_provoking": 5,
            "pacing": 5,
            "writing": 4.5,
            "music_sound": 5.2,
        },
        "historical_score": 96.00,
    },
    {
        "media_type": "video",
        "title": "Lee Kronin's The Mummy",
        "genre": "Horror",
        "date_consumed": "2026-07-12",
        "scores": {
            "entertaining": 3,
            "engaging": 3.5,
            "thought_provoking": 2,
            "pacing": 4.5,
            "writing": 4,
            "music_sound": 3.75,
        },
        "historical_score": 69.17,
    },
    {
        "media_type": "video",
        "title": "Hades Town",
        "genre": "Musical / Tragedy",
        "date_consumed": "2026-07-25",
        "scores": {
            "entertaining": 5,
            "engaging": 4.8,
            "thought_provoking": 4.5,
            "pacing": 4.9,
            "writing": 5,
            "music_sound": 5,
        },
        "historical_score": 97.33,
    },
    {
        "media_type": "video",
        "title": "Is god is",
        "genre": "Revenge / Action",
        "date_consumed": "2026-08-02",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.75,
            "thought_provoking": 4,
            "pacing": 4.25,
            "writing": 4.5,
            "music_sound": 5,
        },
        "historical_score": 90.00,
    },
    {
        "media_type": "video",
        "title": "The Long Walk",
        "genre": "Distopian / Drama",
        "date_consumed": "2026-08-05",
        "scores": {
            "entertaining": 4.5,
            "engaging": 4.5,
            "thought_provoking": 4.9,
            "pacing": 4.9,
            "writing": 4.9,
            "music_sound": 4.8,
        },
        "historical_score": 95.00,
    },

    # ------------------------------------------------------------------
    # BOOKS
    # ------------------------------------------------------------------
    {
        "media_type": "book",
        "title": "Recursion",
        "genre": "Novel",
        "date_consumed": "2026-03-20",
        "method": "Physical Book",
        "author": "Blake Crouch",
        "scores": {
            "entertainment": 5,
            "engaging": 5,
            "thought_provoking": 4.8,
            "pacing": 5,
            "concept_originality": 5,
            "writing_quality": 4.8,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 99.00,
    },
    {
        "media_type": "book",
        "title": "Strange Pictures",
        "genre": "Novel",
        "date_consumed": "2026-03-23",
        "method": "Physical Book",
        "author": "Uketsu",
        "scores": {
            "entertainment": 4.8,
            "engaging": 4.8,
            "thought_provoking": 5,
            "pacing": 4.8,
            "concept_originality": 5,
            "writing_quality": 4.9,
            "emotional_psychological_impact": 4.75,
            "mystery_curiosity": 4.9,
        },
        "historical_score": 97.38,
    },
    {
        "media_type": "book",
        "title": "Project Hail Mary",
        "genre": "Novel",
        "date_consumed": "2026-03-25",
        "method": "Physical Book",
        "author": "Andy Weir",
        "scores": {
            "entertainment": 4.8,
            "engaging": 4.9,
            "thought_provoking": 4.5,
            "pacing": 5,
            "concept_originality": 4.8,
            "writing_quality": 4.9,
            "emotional_psychological_impact": 4.9,
            "mystery_curiosity": 4.8,
        },
        "historical_score": 96.50,
    },
    {
        "media_type": "book",
        "title": "Dark Matter",
        "genre": "Novel",
        "date_consumed": "2026-03-27",
        "method": "Physical Book",
        "author": "Blake Crouch",
        "scores": {
            "entertainment": 4.5,
            "engaging": 5,
            "thought_provoking": 4,
            "pacing": 5,
            "concept_originality": 4.5,
            "writing_quality": 5,
            "emotional_psychological_impact": 4.8,
            "mystery_curiosity": 4.8,
        },
        "historical_score": 94.00,
    },
    {
        "media_type": "book",
        "title": "There is No Antimemetics Division",
        "genre": "Novel",
        "date_consumed": "2026-03-30",
        "method": "Physical Book",
        "author": "QNTM",
        "scores": {
            "entertainment": 4.25,
            "engaging": 4.25,
            "thought_provoking": 5.1,
            "pacing": 4,
            "concept_originality": 5.25,
            "writing_quality": 4,
            "emotional_psychological_impact": 4.8,
            "mystery_curiosity": 5,
        },
        "historical_score": 91.63,
    },
    {
        "media_type": "book",
        "title": "Annihilation",
        "genre": "Novel",
        "date_consumed": "2026-04-01",
        "method": "Physical Book",
        "author": "Jeff Vandermeer",
        "scores": {
            "entertainment": 4.5,
            "engaging": 4.8,
            "thought_provoking": 5,
            "pacing": 4.7,
            "concept_originality": 5,
            "writing_quality": 4.5,
            "emotional_psychological_impact": 4.75,
            "mystery_curiosity": 5.1,
        },
        "historical_score": 95.88,
    },
    {
        "media_type": "book",
        "title": "Dungeon Crawler Carl",
        "genre": "Novel",
        "date_consumed": "2026-04-08",
        "method": "Physical Book",
        "author": "Matt Dinniman",
        "scores": {
            "entertainment": 5.1,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "concept_originality": 5,
            "writing_quality": 5,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 100.25,
    },
    {
        "media_type": "book",
        "title": "Carl's Doomsday Scenario",
        "genre": "Novel",
        "date_consumed": "2026-04-11",
        "method": "Physical Book",
        "author": "Matt Dinniman",
        "scores": {
            "entertainment": 5.2,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "concept_originality": 5,
            "writing_quality": 5,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 100.50,
    },
    {
        "media_type": "book",
        "title": "The Dungeon Anarchist's Cook-Book",
        "genre": "Novel",
        "date_consumed": "2026-04-17",
        "method": "Physical Book",
        "author": "Matt Dinniman",
        "scores": {
            "entertainment": 5,
            "engaging": 4.9,
            "thought_provoking": 4.99,
            "pacing": 4.99,
            "concept_originality": 5,
            "writing_quality": 5,
            "emotional_psychological_impact": 5.25,
            "mystery_curiosity": 5,
        },
        "historical_score": 100.33,
    },
    {
        "media_type": "book",
        "title": "A Short Stay in Hell",
        "genre": "Novel",
        "date_consumed": "2026-04-18",
        "method": "Digital Book",
        "author": "Steven L Peck",
        "scores": {
            "entertainment": 5,
            "engaging": 5,
            "thought_provoking": 4.75,
            "pacing": 4.9,
            "concept_originality": 4.9,
            "writing_quality": 5,
            "emotional_psychological_impact": 5.25,
            "mystery_curiosity": 5,
        },
        "historical_score": 99.50,
    },
    {
        "media_type": "book",
        "title": "The Gate of the Feral Gods",
        "genre": "Novel",
        "date_consumed": "2026-05-05",
        "method": "Physical Book",
        "author": "Matt Dinniman",
        "scores": {
            "entertainment": 5,
            "engaging": 5,
            "thought_provoking": 4.8,
            "pacing": 4.8,
            "concept_originality": 4.85,
            "writing_quality": 5,
            "emotional_psychological_impact": 5.1,
            "mystery_curiosity": 5,
        },
        "historical_score": 98.88,
    },
    {
        "media_type": "book",
        "title": "Piranesi",
        "genre": "Novel",
        "date_consumed": "2026-05-07",
        "method": "Physical Book",
        "author": "Susanna Clark",
        "scores": {
            "entertainment": 4.9,
            "engaging": 5,
            "thought_provoking": 4.95,
            "pacing": 4.8,
            "concept_originality": 5,
            "writing_quality": 4.9,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 98.88,
    },
    {
        "media_type": "book",
        "title": "The Butcher's Masquerade",
        "genre": "Novel",
        "date_consumed": "2026-05-24",
        "method": "Physical Book",
        "author": "Matt Dinniman",
        "scores": {
            "entertainment": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 5,
            "concept_originality": 4.85,
            "writing_quality": 4.9,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 99.38,
    },
    {
        "media_type": "book",
        "title": "House of Leaves",
        "genre": "Novel",
        "date_consumed": "2026-06-15",
        "method": "Physical Book",
        "author": "Mark Z. Danielewski",
        "scores": {
            "entertainment": 5,
            "engaging": 5,
            "thought_provoking": 5,
            "pacing": 4.8,
            "concept_originality": 5,
            "writing_quality": 5,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 99.50,
    },
    {
        "media_type": "book",
        "title": "Strange Houses",
        "genre": "Novel",
        "date_consumed": "2026-06-17",
        "method": "Physical Book",
        "author": "Uketsu",
        "scores": {
            "entertainment": 4.5,
            "engaging": 4.5,
            "thought_provoking": 5,
            "pacing": 4,
            "concept_originality": 4.8,
            "writing_quality": 4.75,
            "emotional_psychological_impact": 4.75,
            "mystery_curiosity": 4.9,
        },
        "historical_score": 93.00,
    },
    {
        "media_type": "book",
        "title": "Vita Nostra",
        "genre": "Novel",
        "date_consumed": "2026-06-24",
        "method": "Digital Book",
        "author": "Marina and Sergey Dyachenko",
        "scores": {
            "entertainment": 4.25,
            "engaging": 4.5,
            "thought_provoking": 4.4,
            "pacing": 4,
            "concept_originality": 4.75,
            "writing_quality": 4.5,
            "emotional_psychological_impact": 5,
            "mystery_curiosity": 5,
        },
        "historical_score": 91.00,
    },
]

HISTORICAL_UNFINISHED_GAMES = [
    {
        "title": "Mega Man 8",
        "media_type": "game",
        "system": "PSX",
        "hardware": "R36s",
    },
    {
        "title": "Mario Kart 64",
        "media_type": "game",
        "system": "N64",
        "hardware": "R36s",
    },
    {
        "title": "Mario Kart 7",
        "media_type": "game",
        "system": "3DS",
        "hardware": "3DS",
    },
    {
        "title": "Little Samson",
        "media_type": "game",
        "system": "NES",
        "hardware": "3DS",
    },
    {
        "title": "Pokemon Pinball",
        "media_type": "game",
        "system": "GBC",
        "hardware": "R36s",
    },
    {
        "title": "The Starship Damrey",
        "media_type": "game",
        "system": "3DS",
        "hardware": "3DS",
    },
    {
        "title": "Diddy Kong Racing",
        "media_type": "game",
        "system": "NDS",
        "hardware": "NDS",
    },
    {
        "title": "Chrono Trigger",
        "media_type": "game",
        "system": "SNES",
        "hardware": "R36s",
    },
    {
        "title": "The World Ends with You",
        "media_type": "game",
        "system": "NDS",
        "hardware": "NDS",
    },
    {
        "title": "Super Mario 64",
        "media_type": "game",
        "system": "N64",
        "hardware": "PC",
    },
    {
        "title": "LoZ A Link to the Past",
        "media_type": "game",
        "system": "SNES",
        "hardware": "PC",
    },
    {
        "title": "LoZ Phantom Hourglass",
        "media_type": "game",
        "system": "NDS",
        "hardware": "NDS",
    },
    {
        "title": "Wario Ware Touched",
        "media_type": "game",
        "system": "NDS",
        "hardware": "NDS",
    },
    {
        "title": "Kirby's Pinball Land",
        "media_type": "game",
        "system": "NES",
        "hardware": "R36s",
    },
    {
        "title": "Theresia",
        "media_type": "game",
        "system": "NDS",
        "hardware": "NDS",
    },
    {
        "title": "Ever Oasis",
        "media_type": "game",
        "system": "3DS",
        "hardware": "3DS",
    },
    {
        "title": "Kirby's Dream Land II",
        "media_type": "game",
        "system": "GB",
        "hardware": "R36s",
    },
    {
        "title": "SMT IV",
        "media_type": "game",
        "system": "3DS",
        "hardware": "3DS",
    },
    {
        "title": "Mother 3",
        "media_type": "game",
        "system": "GBA",
        "hardware": "R36s",
    },
]

HISTORICAL_UNFINISHED_BOOKS = [
    {
        "title": "The Raw Shark Texts",
        "media_type": "book",
    },
    {
        "title": "Night Film",
        "media_type": "book",
    },
    {
        "title": "The Night Circus",
        "media_type": "book",
    },
    {
        "title": "Thirteen Stories",
        "media_type": "book",
    },
]
