SCORING_RUBRIC = {
    1: "Terrible — fundamentally fails; little to no redeeming value.",
    2: "Very poor — major problems dominate the experience.",
    3: "Poor — significant weaknesses outweigh the strengths.",
    4: "Below average — some worthwhile qualities, but clearly flawed.",
    5: "Okay — acceptable and functional, but neither notably good nor bad.",
    6: "Decent — more strengths than weaknesses, but still noticeably limited.",
    7: "Good — clearly successful with meaningful strengths and relatively minor flaws.",
    8: "Very good — strong execution with only a few notable weaknesses.",
    9: "Excellent — exceptional quality with very little meaningful room for improvement.",
    10: "No improvement possible — essentially perfect for the category being scored.",
}


def get_score_meaning(score):
    return SCORING_RUBRIC.get(score)


METRIC_RUBRICS = {
    "depth": {
        1: "Ask whether the work is almost entirely surface-level, with little meaningful substance to interpret or consider.",
        2: "Ask whether there are major limitations in the work's ideas, themes, or substance, with little beyond the immediate experience.",
        3: "Ask whether the work has some meaningful ideas or themes, but whether they are underdeveloped, obvious, or inconsistently handled.",
        4: "Ask whether the work offers some substance to think about, but whether its ideas remain fairly limited, straightforward, or shallow.",
        5: "Ask whether the work provides an acceptable amount of substance and meaning, without offering especially substantial layers of interpretation.",
        6: "Ask whether the work offers meaningful ideas, themes, or layers that go beyond the surface, even if those elements are not especially developed or complex.",
        7: "Ask whether the work presents strong ideas, themes, or layers that reward attention and interpretation, with only some limitations in depth or development.",
        8: "Ask whether the work demonstrates substantial ideas, themes, or layers that meaningfully reward interpretation and reflection, with relatively minor limitations.",
        9: "Ask whether the work is exceptionally rich in ideas, themes, or layers, repeatedly rewarding analysis and revealing meaningful depth with very few shortcomings.",
        10: "Ask whether the work offers essentially limitless meaningful interpretation or extraordinary conceptual depth, with no meaningful improvement possible in this category.",
    },
    "craft": {
        1: "Ask whether the work's execution is fundamentally poor, with pervasive technical or artistic weaknesses that substantially undermine the experience.",
        2: "Ask whether major execution problems are consistently visible across the work, with only limited evidence of effective craftsmanship.",
        3: "Ask whether the work demonstrates some competent execution, but whether noticeable technical or artistic weaknesses frequently interfere with the experience.",
        4: "Ask whether the work is competently made overall, but whether execution is inconsistent or limited in ways that noticeably hold it back.",
        5: "Ask whether the work demonstrates acceptable craftsmanship without being particularly polished, refined, or technically impressive.",
        6: "Ask whether the work is well executed in most respects, with clear evidence of care and competence despite some noticeable limitations.",
        7: "Ask whether the work demonstrates strong and consistent craftsmanship, with relatively few execution problems.",
        8: "Ask whether the work demonstrates very strong craftsmanship, with polished execution and only relatively minor weaknesses.",
        9: "Ask whether the work demonstrates exceptional craftsmanship across nearly every relevant aspect, with very few meaningful execution flaws.",
        10: "Ask whether the execution is essentially exemplary for its medium and purpose, leaving no meaningful room for improvement in craftsmanship.",
    },
    "engagement": {
        1: "Ask whether the work consistently fails to hold attention or generate interest, making continued engagement difficult.",
        2: "Ask whether the work rarely sustains interest and frequently loses attention despite occasional engaging moments.",
        3: "Ask whether the work provides some engaging moments, but whether interest frequently drops or requires significant effort to maintain.",
        4: "Ask whether the work is intermittently engaging, with enough moments of interest to remain watchable or playable but substantial stretches that fail to hold attention.",
        5: "Ask whether the work maintains an acceptable level of engagement overall, without being especially compelling or difficult to put down.",
        6: "Ask whether the work generally holds attention and creates a meaningful desire to continue, despite some slower or less engaging stretches.",
        7: "Ask whether the work consistently holds attention and creates a strong desire to continue, with relatively few disengaging moments.",
        8: "Ask whether the work is highly engaging, consistently maintaining interest and momentum while making continued attention feel natural rather than effortful.",
        9: "Ask whether the work is exceptionally compelling, sustaining attention almost continuously and creating a strong pull to keep experiencing it.",
        10: "Ask whether the work is virtually impossible to improve in terms of engagement, maintaining exceptional attention and investment throughout with no meaningful loss of interest.",
    },
    "emotional_impact": {
        1: "Ask whether the work produces little to no meaningful emotional response, with its intended emotional moments failing to connect.",
        2: "Ask whether the work occasionally produces a weak emotional response, but whether most attempts at emotional impact feel ineffective or disconnected.",
        3: "Ask whether the work creates some genuine emotional reactions, but whether they are limited, inconsistent, or quickly forgotten.",
        4: "Ask whether the work has several emotionally effective moments, but whether its overall emotional impact remains fairly modest or inconsistent.",
        5: "Ask whether the work produces an acceptable emotional response, with some moments that connect without leaving a particularly strong or lasting impression.",
        6: "Ask whether the work regularly creates genuine emotional reactions and establishes some meaningful emotional investment, despite noticeable limitations.",
        7: "Ask whether the work creates strong emotional investment and several memorable emotional moments, with relatively few weaknesses.",
        8: "Ask whether the work produces a strong and lasting emotional response, with its emotional moments feeling earned, meaningful, and consistently effective.",
        9: "Ask whether the work is exceptionally emotionally resonant, producing powerful and memorable reactions that remain significant after the experience ends.",
        10: "Ask whether the work achieves essentially unparalleled emotional resonance for its purpose, leaving no meaningful room for improvement in emotional impact.",
    },
    "presentation": {
        1: "Ask whether the work's presentation is consistently distracting, confusing, or poorly executed enough to substantially interfere with the experience.",
        2: "Ask whether major presentation problems are frequently distracting, with only limited evidence of effective visual, structural, or sensory presentation.",
        3: "Ask whether the work is generally understandable but has frequent presentation weaknesses that noticeably reduce clarity, cohesion, or immersion.",
        4: "Ask whether the work is adequately presented overall, but whether inconsistencies or limitations are frequently noticeable.",
        5: "Ask whether the work is presented competently and clearly enough to support the experience, without being especially polished or distinctive.",
        6: "Ask whether the work is well presented in most respects, with effective clarity, cohesion, and sensory or structural choices despite some limitations.",
        7: "Ask whether the work demonstrates strong presentation that consistently supports its intended experience, with relatively few distracting weaknesses.",
        8: "Ask whether the work is highly polished and cohesive in its presentation, with its visual, structural, or sensory choices consistently enhancing the experience.",
        9: "Ask whether the work demonstrates exceptional presentation throughout, with an unusually strong sense of polish, cohesion, and intentionality.",
        10: "Ask whether the presentation is essentially exemplary for the work's medium and purpose, leaving no meaningful room for improvement.",
    },
    "originality": {
        1: "Ask whether the work feels almost entirely derivative, relying heavily on familiar ideas, structures, conventions, or execution without adding a meaningful individual identity.",
        2: "Ask whether the work contains very little that feels distinctive, with most of its ideas or presentation closely resembling familiar existing works.",
        3: "Ask whether the work includes occasional distinctive ideas or choices, but whether its overall identity remains substantially conventional or derivative.",
        4: "Ask whether the work demonstrates some individuality through particular ideas, combinations, or stylistic choices, while remaining mostly familiar in its approach.",
        5: "Ask whether the work has a recognizable individual identity and some fresh ideas or combinations, without being especially novel or groundbreaking.",
        6: "Ask whether the work regularly introduces distinctive ideas, combinations, perspectives, or stylistic choices that meaningfully differentiate it from familiar works.",
        7: "Ask whether the work demonstrates strong originality, with multiple ideas or approaches that feel genuinely distinctive and contribute meaningfully to its identity.",
        8: "Ask whether the work consistently demonstrates a highly distinctive creative identity, combining ideas or approaches in ways that feel fresh and meaningfully uncommon.",
        9: "Ask whether the work is exceptionally original, introducing or combining ideas, perspectives, systems, or stylistic approaches in ways that feel genuinely rare and difficult to mistake for conventional work.",
        10: "Ask whether the work achieves essentially unmatched originality for its purpose, presenting a remarkably distinctive creative identity with no meaningful room for greater novelty or individuality.",
    },
    "prose_writing": {
        1: "Ask whether the prose is consistently unclear, awkward, distracting, or poorly constructed enough to substantially interfere with the reading experience.",
        2: "Ask whether major problems with clarity, sentence construction, diction, or style occur frequently, with very little effective writing to offset them.",
        3: "Ask whether the prose is generally understandable but frequently suffers from awkwardness, inconsistency, blandness, or other noticeable weaknesses.",
        4: "Ask whether the writing is competent enough to communicate its ideas, but whether its style, voice, or sentence-level execution is often limited or unremarkable.",
        5: "Ask whether the prose is clear and competent overall, providing an acceptable reading experience without being especially distinctive or impressive.",
        6: "Ask whether the writing is consistently effective, with a recognizable voice, good clarity, and generally strong sentence-level execution despite some limitations.",
        7: "Ask whether the prose demonstrates a strong and confident voice, effective language choices, and consistently polished writing with relatively few weaknesses.",
        8: "Ask whether the prose is highly polished and expressive, with a distinctive voice and consistently effective use of language that meaningfully enhances the work.",
        9: "Ask whether the writing is exceptionally accomplished, demonstrating remarkable control of voice, language, rhythm, and style with very few meaningful weaknesses.",
        10: "Ask whether the prose is essentially exemplary for its intended style and purpose, leaving no meaningful room for improvement in the quality or effectiveness of the writing.",
    },
    "character_development": {
        1: "Ask whether the characters are consistently flat, poorly defined, or function primarily as plot devices, with little meaningful characterization.",
        2: "Ask whether most characters have very limited identities, motivations, or development, with only occasional hints of meaningful characterization.",
        3: "Ask whether some characters have recognizable personalities or motivations, but whether development is shallow, inconsistent, or heavily dependent on familiar archetypes.",
        4: "Ask whether the characters are generally functional and understandable, but whether their development, complexity, or individuality is limited.",
        5: "Ask whether the characters are competently characterized, with understandable motivations and some meaningful individuality, without being especially complex or transformative.",
        6: "Ask whether the characters demonstrate meaningful individuality, believable motivations, and noticeable development, despite some limitations in complexity or consistency.",
        7: "Ask whether the characters are strongly developed, distinct, and emotionally or psychologically convincing, with clear growth or meaningful internal complexity.",
        8: "Ask whether the characters demonstrate substantial depth, individuality, and development, with their choices, relationships, and changes meaningfully enriching the work.",
        9: "Ask whether the characterization is exceptionally rich and nuanced, with highly distinctive characters whose motivations, relationships, and development feel consistently authentic and consequential.",
        10: "Ask whether the character work is essentially exemplary, providing extraordinary depth, individuality, development, and psychological or emotional authenticity with no meaningful room for improvement.",
    },
    "world_building": {
        1: "Ask whether the setting is poorly defined, inconsistent, or almost entirely dependent on generic conventions, providing little sense of a coherent world beyond the immediate plot.",
        2: "Ask whether the work establishes only a minimal setting, with major gaps, inconsistencies, or generic elements that limit the sense of an actual world.",
        3: "Ask whether the setting has some identifiable details or ideas, but whether the world remains shallow, inconsistent, underdeveloped, or heavily familiar.",
        4: "Ask whether the world is functional and understandable, but whether its history, cultures, systems, environments, or internal logic remain relatively limited.",
        5: "Ask whether the work establishes a coherent and sufficiently developed world that supports the story, without being especially rich or distinctive.",
        6: "Ask whether the world demonstrates meaningful detail, internal logic, and context that enrich the experience, despite some limitations or unexplored areas.",
        7: "Ask whether the world feels strongly realized, coherent, and lived-in, with its systems, history, cultures, environments, or rules meaningfully supporting the experience.",
        8: "Ask whether the world demonstrates substantial richness and internal coherence, with details and systems that feel purposeful, interconnected, and meaningfully integrated into the work.",
        9: "Ask whether the world is exceptionally rich, coherent, distinctive, and deeply integrated, creating a convincing sense of history, culture, systems, and life beyond what is directly presented.",
        10: "Ask whether the world-building is essentially exemplary, presenting an extraordinarily coherent, rich, distinctive, and fully realized world with no meaningful room for improvement.",
    },
    "narrative_pacing": {
        1: "Ask whether the narrative's timing is consistently ineffective, with excessive dragging, rushing, or structural imbalance that substantially harms the experience.",
        2: "Ask whether major pacing problems frequently disrupt the experience, with important material rushed and/or unimportant material receiving excessive attention.",
        3: "Ask whether the pacing works in some stretches but frequently becomes sluggish, rushed, uneven, or poorly balanced.",
        4: "Ask whether the narrative generally moves forward adequately, but whether noticeable pacing problems regularly weaken tension, momentum, or narrative focus.",
        5: "Ask whether the pacing is competent and generally appropriate to the material, without being especially dynamic, controlled, or effective.",
        6: "Ask whether the narrative generally allocates time effectively, allowing important moments room to develop while maintaining reasonable momentum despite some unevenness.",
        7: "Ask whether the pacing is consistently well controlled, balancing development, tension, transitions, and momentum with relatively few weak stretches.",
        8: "Ask whether the narrative demonstrates highly effective pacing, giving each major development appropriate weight while maintaining strong momentum and allowing important moments to breathe.",
        9: "Ask whether the pacing is exceptionally controlled and purposeful, with nearly every section receiving exactly the amount of narrative attention it needs to maximize tension, development, and momentum.",
        10: "Ask whether the pacing is essentially exemplary for the work's intended experience, with no meaningful sections that could be slowed down, accelerated, expanded, or condensed for improvement.",
    },
    "cinematography_visuals": {
        1: "Ask whether the visual presentation is consistently poorly composed, distracting, unclear, or ineffective, substantially undermining the experience.",
        2: "Ask whether major visual weaknesses are frequent, with limited evidence of effective composition, lighting, imagery, or visual storytelling.",
        3: "Ask whether the work contains some effective visual moments, but whether its cinematography or visual presentation is frequently inconsistent, generic, or poorly controlled.",
        4: "Ask whether the visual presentation is generally functional and understandable, but whether composition, lighting, camera work, or visual cohesion are noticeably limited.",
        5: "Ask whether the visuals are competent and adequately support the work, without being especially distinctive, polished, or visually expressive.",
        6: "Ask whether the work demonstrates generally strong visual execution, with effective composition, lighting, imagery, and visual coherence despite some limitations.",
        7: "Ask whether the cinematography and visual presentation consistently enhance the experience through strong composition, lighting, camera work, and intentional visual choices.",
        8: "Ask whether the visual language is highly polished and expressive, using composition, lighting, movement, imagery, and visual design to meaningfully strengthen the work.",
        9: "Ask whether the cinematography and visual presentation are exceptionally accomplished, demonstrating remarkable control, intentionality, and visual storytelling with very few meaningful weaknesses.",
        10: "Ask whether the visual execution is essentially exemplary for its intended style and purpose, leaving no meaningful room for improvement in cinematography or visual presentation.",
    },
    "acting_performances": {
        1: "Ask whether the performances are consistently unconvincing, distracting, or poorly matched to the material, substantially undermining the experience.",
        2: "Ask whether major performance weaknesses are frequent, with limited evidence of believable characterization, emotional expression, or effective delivery.",
        3: "Ask whether some performances or moments are effective, but whether performances are frequently uneven, artificial, flat, or poorly matched to the material.",
        4: "Ask whether the performances are generally functional and understandable, but whether emotional delivery, characterization, chemistry, or consistency are noticeably limited.",
        5: "Ask whether the performances are competent and adequately serve the material, without being especially memorable, nuanced, or compelling.",
        6: "Ask whether the performances are generally convincing and effective, with believable characterization and emotional delivery despite some limitations.",
        7: "Ask whether the performances consistently demonstrate strong characterization, emotional authenticity, chemistry, and effective delivery with relatively few weak points.",
        8: "Ask whether the performances are highly accomplished, bringing substantial nuance, emotional depth, individuality, and credibility to the material.",
        9: "Ask whether the performances are exceptionally powerful and nuanced, demonstrating remarkable control, authenticity, chemistry, and emotional range with very few meaningful weaknesses.",
        10: "Ask whether the performances are essentially exemplary for the material, achieving extraordinary authenticity, nuance, emotional expression, and characterization with no meaningful room for improvement.",
    },
    "directing_editing": {
        1: "Ask whether the direction and editing are consistently confusing, poorly controlled, or structurally ineffective, substantially undermining the experience.",
        2: "Ask whether major problems with scene construction, transitions, rhythm, continuity, or overall direction occur frequently and noticeably disrupt the work.",
        3: "Ask whether some sequences are effectively directed or edited, but whether the overall execution is frequently uneven, awkward, or lacking in clear intentionality.",
        4: "Ask whether the direction and editing are generally functional, but whether noticeable weaknesses in structure, rhythm, transitions, continuity, or scene construction regularly reduce effectiveness.",
        5: "Ask whether the work is competently directed and edited, communicating its intended story and maintaining an acceptable rhythm without being especially distinctive or polished.",
        6: "Ask whether the direction and editing generally create a coherent and effective experience, with good control of scenes, transitions, rhythm, and narrative focus despite some limitations.",
        7: "Ask whether the work demonstrates strong directorial and editorial control, consistently shaping performances, scenes, transitions, rhythm, and narrative focus effectively.",
        8: "Ask whether the direction and editing are highly accomplished, demonstrating strong intentionality, rhythm, structural control, and integration of the work's individual elements.",
        9: "Ask whether the directing and editing are exceptionally controlled and purposeful, with remarkable command of structure, rhythm, transitions, performances, and visual storytelling.",
        10: "Ask whether the direction and editing are essentially exemplary for the intended experience, achieving extraordinary coherence, rhythm, structure, and integration with no meaningful room for improvement.",
    },
    "sound_music": {
        1: "Ask whether the sound and music are consistently distracting, poorly executed, unclear, or ineffective, substantially undermining the experience.",
        2: "Ask whether major problems with sound quality, dialogue clarity, sound design, music, or audio balance occur frequently and noticeably weaken the work.",
        3: "Ask whether some audio elements are effective, but whether the overall sound and music are frequently uneven, generic, distracting, or poorly integrated.",
        4: "Ask whether the audio presentation is generally functional, but whether noticeable weaknesses in sound design, music, dialogue clarity, balance, or integration regularly reduce effectiveness.",
        5: "Ask whether the sound and music are competent and adequately support the work, without being especially distinctive, immersive, or memorable.",
        6: "Ask whether the audio presentation generally enhances the experience through effective sound design, music, dialogue, ambience, and balance despite some limitations.",
        7: "Ask whether sound and music are consistently well integrated, using audio design, musical choices, ambience, silence, and effects to meaningfully strengthen the work.",
        8: "Ask whether the audio experience is highly accomplished and expressive, with strong sound design, musical integration, atmosphere, clarity, and intentional use of silence or dynamics.",
        9: "Ask whether the sound and music are exceptionally accomplished, demonstrating remarkable control, creativity, atmosphere, and integration with the work's emotional and narrative goals.",
        10: "Ask whether the audio execution is essentially exemplary for the intended experience, with extraordinary sound design, music, atmosphere, clarity, and integration leaving no meaningful room for improvement.",
    },
    "gameplay_mechanics": {
        1: "Ask whether the core mechanics are fundamentally broken, unresponsive, incoherent, or so poorly designed that meaningful interaction is consistently undermined.",
        2: "Ask whether major mechanical problems, poor controls, weak feedback, severe imbalance, or shallow systems frequently interfere with the basic gameplay experience.",
        3: "Ask whether the mechanics are functional but frequently repetitive, shallow, awkward, poorly balanced, or insufficiently developed.",
        4: "Ask whether the core mechanics are generally functional and playable, but whether noticeable weaknesses in responsiveness, depth, balance, feedback, or mechanical cohesion limit the experience.",
        5: "Ask whether the mechanics are competent and functional, providing a reasonably coherent interactive experience without being especially deep, inventive, responsive, or refined.",
        6: "Ask whether the mechanics are generally well-designed and satisfying, with effective controls, feedback, balance, and enough depth to support the intended experience.",
        7: "Ask whether the mechanics are consistently strong, responsive, coherent, and meaningfully interconnected, with thoughtful systems that reward understanding and mastery.",
        8: "Ask whether the gameplay systems are highly accomplished, offering substantial depth, excellent responsiveness, meaningful choices, strong feedback, and well-integrated mechanics.",
        9: "Ask whether the mechanics are exceptionally designed, demonstrating remarkable depth, precision, balance, systemic interaction, and mastery of player-facing design.",
        10: "Ask whether the gameplay mechanics represent an essentially exemplary interactive system, with extraordinary responsiveness, depth, coherence, balance, feedback, and systemic design leaving no meaningful room for improvement.",
    },
    "level_design_progression": {
        1: "The levels, encounters, or progression are fundamentally broken, incoherent, or frustrating, with poor structure and little meaningful development.",
        2: "The game has major problems with level structure, difficulty, pacing, progression, or encounter design that frequently undermine the experience.",
        3: "The progression is functional but frequently repetitive, poorly paced, unevenly balanced, or lacking meaningful development.",
        4: "The progression is generally playable but has noticeable weaknesses in level structure, difficulty curve, pacing, rewards, or the introduction of mechanics.",
        5: "The levels and progression are competent and functional, providing a reasonably coherent journey without being especially inventive, elegant, or well-refined.",
        6: "The progression is generally well-designed, with effective level structure, pacing, difficulty, and mechanical introduction that support the intended experience.",
        7: "The game demonstrates consistently strong level and progression design, with thoughtful escalation, meaningful variety, and mechanics that build naturally on one another.",
        8: "The level design and progression are highly accomplished, with excellent pacing, encounter structure, difficulty development, rewards, and meaningful mechanical evolution.",
        9: "The progression is exceptionally designed, demonstrating remarkable control of pacing, level structure, difficulty, variety, and the introduction and mastery of mechanics.",
        10: "The level design and progression represent an essentially exemplary journey, with extraordinary structure, pacing, escalation, variety, rewards, and mechanical development leaving no meaningful room for improvement.",
    },
    "replayability_systems": {
        1: "Ask whether the game offers essentially no meaningful reason to replay, experiment, optimize, or explore its systems, with repetition quickly becoming empty or redundant.",
        2: "Ask whether replay value is very limited, relying mostly on repetition or superficial variation with little meaningful systemic depth.",
        3: "Ask whether the game provides some replay value through alternate choices, experimentation, collectibles, challenge, or variation, but whether these opportunities are shallow or quickly exhausted.",
        4: "Ask whether there are recognizable reasons to return, but whether replayability is limited by repetitive content, weak systemic depth, or largely superficial variation.",
        5: "Ask whether the game provides a reasonable amount of replay value through its systems, choices, challenges, or discoverable content without being especially deep or expansive.",
        6: "Ask whether the game's systems provide meaningful reasons to return, experiment, optimize, explore alternate approaches, or pursue additional content.",
        7: "Ask whether the game demonstrates strong systemic replayability, with meaningful variation, experimentation, mastery, alternate approaches, or discovery that rewards returning.",
        8: "Ask whether the game offers substantial replay value through interconnected systems, meaningful choices, emergent possibilities, challenge, experimentation, or significant alternate experiences.",
        9: "Ask whether the replayability is exceptionally strong, with highly developed systems that support extensive experimentation, mastery, discovery, optimization, or genuinely distinct play experiences.",
        10: "Ask whether the game's replayability systems are essentially exemplary, providing extraordinary depth, variation, experimentation, mastery, and discovery with no meaningful room for improvement.",
    },
    "art_atmosphere": {
        1: "Ask whether the game's visual and atmospheric presentation is consistently distracting, incoherent, poorly executed, or ineffective, substantially undermining the experience.",
        2: "Ask whether major weaknesses in art direction, atmosphere, environmental presentation, audio atmosphere, or visual cohesion frequently diminish the experience.",
        3: "Ask whether some visual or atmospheric elements are effective, but whether the overall presentation is frequently generic, uneven, poorly integrated, or lacking in clear identity.",
        4: "Ask whether the game's presentation is generally functional, but whether noticeable weaknesses in art direction, atmosphere, environmental detail, audio ambience, or visual cohesion limit its impact.",
        5: "Ask whether the game's art direction and atmosphere are competent and adequately support the experience, without being especially distinctive, immersive, or cohesive.",
        6: "Ask whether the game demonstrates generally strong art direction and atmosphere, with effective visual identity, environmental presentation, soundscape, and mood despite some limitations.",
        7: "Ask whether the game's artistic direction and atmosphere consistently strengthen the experience through cohesive visual identity, environmental storytelling, sound, mood, and intentional presentation.",
        8: "Ask whether the art direction and atmosphere are highly accomplished, creating a distinctive, immersive, and cohesive sensory identity that meaningfully enhances the game's systems and world.",
        9: "Ask whether the game's artistic and atmospheric execution is exceptionally accomplished, demonstrating remarkable cohesion, intentionality, environmental identity, mood, and sensory storytelling.",
        10: "Ask whether the art direction and atmosphere are essentially exemplary for the intended experience, achieving extraordinary visual identity, environmental storytelling, mood, soundscape, and sensory cohesion with no meaningful room for improvement.",
    },
}

CONDENSED_RUBRICS = {
    "depth": {
        1: "Almost entirely surface-level; little meaningful substance",
        2: "Major limitations in ideas, themes, or substance",
        3: "Some meaningful ideas or themes, but shallow or underdeveloped",
        4: "Some substance to consider, but limited or straightforward",
        5: "Adequate substance and meaning, without substantial interpretive layers",
        6: "Meaningful ideas, themes, or layers beyond the surface",
        7: "Strong ideas, themes, or layers that reward interpretation",
        8: "Substantial depth that meaningfully rewards interpretation and reflection",
        9: "Exceptional richness and depth; repeatedly rewards analysis",
        10: "Extraordinary conceptual depth; essentially limitless interpretation",
    },
    "craft": {
        1: "Fundamentally poor execution; pervasive technical or artistic weaknesses",
        2: "Major execution problems dominate; little effective craftsmanship",
        3: "Some competent execution, but frequent technical or artistic weaknesses",
        4: "Competently made, but inconsistent or noticeably limited execution",
        5: "Acceptable craftsmanship; competent but not especially polished",
        6: "Well executed with clear care and competence; some limitations",
        7: "Strong, consistent craftsmanship with relatively few execution problems",
        8: "Very strong craftsmanship; polished execution with minor weaknesses",
        9: "Exceptional craftsmanship with very few meaningful execution flaws",
        10: "Exemplary execution; essentially no room for improvement",
    },
    "engagement": {
        1: "Consistently fails to hold attention; continued engagement is difficult",
        2: "Rarely sustains interest; major stretches lose attention",
        3: "Some engaging moments, but interest frequently drops",
        4: "Intermittently engaging; substantial stretches fail to hold attention",
        5: "Acceptable engagement; neither especially compelling nor difficult to put down",
        6: "Generally holds attention and creates a desire to continue; some slower stretches",
        7: "Consistently holds attention and creates a strong desire to continue",
        8: "Highly engaging; strong interest and momentum feel natural",
        9: "Exceptionally compelling; sustains attention almost continuously",
        10: "Exceptional engagement throughout; essentially no meaningful loss of interest",
    },
    "emotional_impact": {
        1: "Little to no emotional effect",
        2: "Rarely creates an emotional response",
        3: "Some emotional moments, but mostly limited in impact",
        4: "Occasionally affecting, but inconsistent or restrained",
        5: "Adequate emotional impact; neither especially affecting nor detached",
        6: "Meaningfully affecting with several strong emotional moments",
        7: "Strong emotional impact that consistently resonates",
        8: "Highly affecting; creates sustained emotional resonance",
        9: "Exceptionally powerful emotional impact",
        10: "Extraordinary emotional resonance; deeply and consistently affecting",
    },
    "presentation": {
        1: "Poor presentation; distracting or severely compromised",
        2: "Major presentation problems frequently distract",
        3: "Noticeable presentation weaknesses limit the experience",
        4: "Generally functional, but uneven or noticeably dated",
        5: "Adequate presentation; functional without standing out",
        6: "Good presentation with clear strengths and some limitations",
        7: "Strong presentation that consistently supports the experience",
        8: "Very polished presentation with minor weaknesses",
        9: "Exceptional presentation with very few noticeable flaws",
        10: "Outstanding presentation; essentially flawless for its category",
    },
    "originality": {
        1: "Almost entirely derivative; little sense of a distinct identity",
        2: "Heavily familiar with few distinctive elements",
        3: "Some original elements, but largely familiar",
        4: "Occasionally distinctive, but mostly conventional",
        5: "A mix of familiar and original ideas or approaches",
        6: "Several distinctive ideas or approaches stand out",
        7: "Clearly original with a strong individual identity",
        8: "Highly distinctive; frequently feels fresh or unexpected",
        9: "Exceptionally original with a remarkable creative identity",
        10: "Extraordinary originality; feels genuinely unprecedented",
    },
    "prose_writing": {
        1: "Awkward, unclear, or consistently ineffective prose",
        2: "Frequent writing problems disrupt readability",
        3: "Readable but often clumsy, uneven, or generic",
        4: "Competent prose with noticeable weaknesses",
        5: "Solid, functional prose without standing out",
        6: "Well-written with clear strengths and occasional weaknesses",
        7: "Strong, polished prose that consistently serves the work",
        8: "Very strong prose with distinctive voice and control",
        9: "Exceptional prose with remarkable precision and style",
        10: "Outstanding prose; exceptional command of language and voice",
    },
    "character_development": {
        1: "Characters remain flat, static, or severely underdeveloped",
        2: "Limited character development with major weaknesses",
        3: "Some character development, but often shallow or inconsistent",
        4: "Competent development with noticeable limitations",
        5: "Adequate character development without much depth",
        6: "Meaningful development with clear growth or complexity",
        7: "Strong, convincing character development throughout",
        8: "Deep, nuanced development with compelling character arcs",
        9: "Exceptional character development with remarkable depth",
        10: "Extraordinary character development; exceptionally rich and nuanced",
    },
    "world_building": {
        1: "Barely developed setting; little sense of a coherent world",
        2: "Major gaps or weaknesses in the world and its details",
        3: "Some interesting elements, but the world feels shallow",
        4: "Competent world-building with noticeable limitations",
        5: "Adequate setting with enough detail to support the work",
        6: "Meaningful world-building with clear depth and consistency",
        7: "Strong, cohesive world with substantial detail and identity",
        8: "Rich, immersive world with strong internal coherence",
        9: "Exceptional world-building with remarkable depth and detail",
        10: "Extraordinary world-building; exceptionally rich, coherent, and immersive",
    },
    "narrative_pacing": {
        1: "Severely uneven; pacing frequently stalls or rushes",
        2: "Major pacing problems repeatedly disrupt the narrative",
        3: "Often uneven, with noticeable slow or rushed stretches",
        4: "Some pacing problems, but generally workable",
        5: "Adequate pacing; generally steady without standing out",
        6: "Good pacing with only occasional slow or rushed moments",
        7: "Strong pacing that consistently supports narrative momentum",
        8: "Very well paced; transitions and progression feel natural",
        9: "Exceptional pacing with remarkable control of narrative rhythm",
        10: "Outstanding pacing; virtually every moment feels perfectly timed",
    },
    "cinematography_visuals": {
        1: "Poor visual composition; frequently distracting or ineffective",
        2: "Major visual weaknesses limit the experience",
        3: "Some effective imagery, but often unremarkable or uneven",
        4: "Competent visuals with noticeable limitations",
        5: "Adequate visual work without much distinction",
        6: "Strong visuals with clear strengths and some limitations",
        7: "Consistently effective composition and visual storytelling",
        8: "Highly polished and visually expressive",
        9: "Exceptional visual craft with remarkable composition and imagery",
        10: "Extraordinary visual direction; virtually every frame feels intentional",
    },
    "acting_performances": {
        1: "Flat or unconvincing performances consistently undermine the work",
        2: "Frequent performance weaknesses distract from the experience",
        3: "Some effective performances, but often uneven or limited",
        4: "Competent performances with noticeable weaknesses",
        5: "Adequate performances that serve the work without standing out",
        6: "Strong performances with clear strengths and occasional limitations",
        7: "Consistently convincing and effective performances",
        8: "Highly compelling performances with strong nuance and presence",
        9: "Exceptional performances with remarkable range and precision",
        10: "Extraordinary performances; exceptionally convincing and expressive",
    },
    "directing_editing": {
        1: "Poor direction or editing; choices frequently disrupt the experience",
        2: "Major structural or editorial weaknesses undermine the work",
        3: "Some effective choices, but often uneven or unfocused",
        4: "Competent direction and editing with noticeable limitations",
        5: "Adequate direction and editing that generally serve the work",
        6: "Strong choices with clear control and occasional weaknesses",
        7: "Consistently effective direction and editing",
        8: "Highly controlled direction and editing with strong visual or narrative flow",
        9: "Exceptional directorial and editorial control",
        10: "Extraordinary direction and editing; virtually every choice feels deliberate",
    },
    "sound_music": {
        1: "Poor sound or music; frequently distracting or ineffective",
        2: "Major audio weaknesses repeatedly undermine the experience",
        3: "Some effective audio, but often uneven or unremarkable",
        4: "Competent sound and music with noticeable limitations",
        5: "Adequate audio that supports the work without standing out",
        6: "Strong sound and music with clear strengths and some limitations",
        7: "Consistently effective audio that enhances the experience",
        8: "Highly polished sound design and music with strong atmosphere",
        9: "Exceptional audio work with remarkable impact and detail",
        10: "Extraordinary sound and music; exceptionally immersive and expressive",
    },
    "gameplay_mechanics": {
        1: "Fundamentally weak mechanics; systems frequently frustrate or fail",
        2: "Major mechanical problems repeatedly hinder play",
        3: "Some effective mechanics, but frequent weaknesses or rough edges",
        4: "Competent mechanics with noticeable limitations",
        5: "Adequate mechanics that function without standing out",
        6: "Strong mechanics with clear strengths and some limitations",
        7: "Well-designed mechanics that consistently support play",
        8: "Highly polished mechanics with strong depth and responsiveness",
        9: "Exceptional mechanics with remarkable depth and refinement",
        10: "Extraordinary mechanics; exceptionally deep, cohesive, and refined",
    },
    "level_design_progression": {
        1: "Poorly structured levels or progression; frequently frustrating",
        2: "Major design or progression problems disrupt play",
        3: "Some effective design, but often uneven or repetitive",
        4: "Competent design with noticeable limitations",
        5: "Adequate level design and progression that generally work",
        6: "Strong layouts and progression with clear strengths",
        7: "Well-designed levels and progression that consistently reward play",
        8: "Highly polished layouts with strong flow and progression",
        9: "Exceptional level design and progression with remarkable cohesion",
        10: "Extraordinary level design; virtually every area and progression choice feels deliberate",
    },
    "replayability_systems": {
        1: "Little to no replay value; systems offer few reasons to return",
        2: "Very limited replay incentives or meaningful variation",
        3: "Some replay value, but opportunities are limited or repetitive",
        4: "Moderate replay value with noticeable limitations",
        5: "Adequate replay value through existing systems or variation",
        6: "Good replay value with several meaningful reasons to return",
        7: "Strong replay systems that provide substantial reasons to replay",
        8: "Highly replayable with meaningful variety and system depth",
        9: "Exceptional replayability with extensive meaningful variation",
        10: "Extraordinary replay value; systems continually support fresh experiences",
    },
    "art_atmosphere": {
        1: "Weak or incoherent aesthetic; little sense of atmosphere",
        2: "Major artistic weaknesses limit the atmosphere",
        3: "Some effective elements, but the aesthetic feels uneven",
        4: "Competent art direction with noticeable limitations",
        5: "Adequate aesthetic and atmosphere without standing out",
        6: "Strong artistic identity with clear atmospheric strengths",
        7: "Distinctive art direction that consistently creates atmosphere",
        8: "Highly cohesive aesthetic with strong atmospheric impact",
        9: "Exceptional artistic identity and atmospheric depth",
        10: "Extraordinary art direction; exceptionally distinctive and immersive",
    },
}


def get_metric_meaning(metric, score):
    if metric not in METRIC_RUBRICS:
        raise ValueError(f"No rubric defined for metric: {metric}")

    return METRIC_RUBRICS[metric].get(score)


def has_metric_rubric(metric):
    return metric in METRIC_RUBRICS
